/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.LoanManagement.LoanSecurityShortfall
{
    public class LoanManagement_LoanSecurityShortfall_Service : SubServiceBase<ERP_LoanManagement_LoanSecurityShortfall>
    {
        public LoanManagement_LoanSecurityShortfall_Service(ERPNextClient client) : base(_DockType.LoanManagement_LoanSecurityShortfall, client) { }

        protected override ERP_LoanManagement_LoanSecurityShortfall FromERPObject(ERPObject obj)
        {
            return new ERP_LoanManagement_LoanSecurityShortfall(obj);
        }

        /* custom functions can be added here */

    }
}

