/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.LoanManagement.LoanSecurityPledge
{
    public partial class ERP_LoanManagement_LoanSecurityPledge : ERPNextObjectBase
    {
        public ERP_LoanManagement_LoanSecurityPledge() : this(new ERPObject(_DockType.LoanManagement_LoanSecurityPledge)) { }
        public ERP_LoanManagement_LoanSecurityPledge(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_LoanManagement_LoanSecurityPledge>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("applicant_type")]
        public string? ApplicantType
        {
            get { return data.applicant_type; }
            set { data.applicant_type = value; }
        }

        [Column("applicant")]
        public string? Applicant
        {
            get { return data.applicant; }
            set { data.applicant = value; }
        }

        [Column("loan")]
        public string? Loan
        {
            get { return data.loan; }
            set { data.loan = value; }
        }

        [Column("loan_application")]
        public string? LoanApplication
        {
            get { return data.loan_application; }
            set { data.loan_application = value; }
        }

        [Column("company")]
        public string? Company
        {
            get { return data.company; }
            set { data.company = value; }
        }

        [Column("pledge_time")]
        public DateTime? PledgeTime
        {
            get { return data.pledge_time; }
            set { data.pledge_time = value; }
        }

        [Column("status")]
        public string? Status
        {
            get { return data.status; }
            set { data.status = value; }
        }

        [Column("total_security_value")]
        public decimal TotalSecurityValue
        {
            get { return data.total_security_value; }
            set { data.total_security_value = value; }
        }

        [Column("maximum_loan_value")]
        public decimal MaximumLoanValue
        {
            get { return data.maximum_loan_value; }
            set { data.maximum_loan_value = value; }
        }

        [Column("reference_no")]
        public string? ReferenceNo
        {
            get { return data.reference_no; }
            set { data.reference_no = value; }
        }

        [Column("description")]
        public string? Description
        {
            get { return data.description; }
            set { data.description = value; }
        }

        [Column("amended_from")]
        public string? AmendedFrom
        {
            get { return data.amended_from; }
            set { data.amended_from = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

