/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Email.Newsletter
{
    public partial class ERP_Email_Newsletter : ERPNextObjectBase
    {
        public ERP_Email_Newsletter() : this(new ERPObject(_DocType.Email_Newsletter)) { }
        public ERP_Email_Newsletter(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("email_sent_at", "datetime(6)", isNullable: true)]
        public DateTimeOffset? EmailSentAt
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.email_sent_at); }
            set { data.email_sent_at = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("total_recipients", "int(11)", isNullable: false)]
        public int TotalRecipients
        {
            get { return data.total_recipients; }
            set { data.total_recipients = value; }
        }

        [ColumnInfo("email_sent", "int(1)", isNullable: false)]
        public bool EmailSent
        {
            get { return ERPNextConverter.IntToBool((int)data.email_sent); }
            set { data.email_sent = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("sender_name", "varchar(140)", isNullable: true)]
        public string? SenderName
        {
            get { return data.sender_name; }
            set { data.sender_name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("sender_email", "varchar(140)", isNullable: true)]
        public string? SenderEmail
        {
            get { return data.sender_email; }
            set { data.sender_email = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("send_from", "varchar(140)", isNullable: true)]
        public string? SendFrom
        {
            get { return data.send_from; }
            set { data.send_from = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("subject", "text", isNullable: true)]
        public string? Subject
        {
            get { return data.subject; }
            set { data.subject = value; }
        }

        [ColumnInfo("content_type", "varchar(140)", isNullable: true)]
        public string? ContentType
        {
            get { return data.content_type; }
            set { data.content_type = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("message", "longtext", isNullable: true)]
        public string? Message
        {
            get { return data.message; }
            set { data.message = value; }
        }

        [ColumnInfo("message_md", "longtext", isNullable: true)]
        public string? MessageMd
        {
            get { return data.message_md; }
            set { data.message_md = value; }
        }

        [ColumnInfo("message_html", "longtext", isNullable: true)]
        public string? MessageHtml
        {
            get { return data.message_html; }
            set { data.message_html = value; }
        }

        [ColumnInfo("send_unsubscribe_link", "int(1)", isNullable: false)]
        public bool SendUnsubscribeLink
        {
            get { return ERPNextConverter.IntToBool((int)data.send_unsubscribe_link); }
            set { data.send_unsubscribe_link = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("send_webview_link", "int(1)", isNullable: false)]
        public bool SendWebviewLink
        {
            get { return ERPNextConverter.IntToBool((int)data.send_webview_link); }
            set { data.send_webview_link = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("scheduled_to_send", "int(11)", isNullable: false)]
        public int ScheduledToSend
        {
            get { return data.scheduled_to_send; }
            set { data.scheduled_to_send = value; }
        }

        [ColumnInfo("schedule_sending", "int(1)", isNullable: false)]
        public bool ScheduleSending
        {
            get { return ERPNextConverter.IntToBool((int)data.schedule_sending); }
            set { data.schedule_sending = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("schedule_send", "datetime(6)", isNullable: true)]
        public DateTimeOffset? ScheduleSend
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.schedule_send); }
            set { data.schedule_send = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("published", "int(1)", isNullable: false)]
        public bool Published
        {
            get { return ERPNextConverter.IntToBool((int)data.published); }
            set { data.published = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("route", "varchar(140)", isNullable: true)]
        public string? Route
        {
            get { return data.route; }
            set { data.route = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("_user_tags", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [ColumnInfo("_comments", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [ColumnInfo("_assign", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [ColumnInfo("_liked_by", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

