/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Stock.ItemSupplier
{
    public class Stock_ItemSupplier_Service : SubServiceBase<ERP_Stock_ItemSupplier>
    {
        public Stock_ItemSupplier_Service(ERPNextClient client) : base(_DockType.Stock_ItemSupplier, client) { }

        protected override ERP_Stock_ItemSupplier FromERPObject(ERPObject obj)
        {
            return new ERP_Stock_ItemSupplier(obj);
        }

        /* custom functions can be added here */

    }
}

