/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Setup.EmployeeEducation
{
    public partial class ERP_Setup_EmployeeEducation : ERPNextObjectBase
    {
        public ERP_Setup_EmployeeEducation() : this(new ERPObject(_DocType.Setup_EmployeeEducation)) { }
        public ERP_Setup_EmployeeEducation(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("school_univ", "text", isNullable: true)]
        public string? SchoolUniv
        {
            get { return data.school_univ; }
            set { data.school_univ = value; }
        }

        [ColumnInfo("qualification", "varchar(140)", isNullable: true)]
        public string? Qualification
        {
            get { return data.qualification; }
            set { data.qualification = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("level", "varchar(140)", isNullable: true)]
        public string? Level
        {
            get { return data.level; }
            set { data.level = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("year_of_passing", "int(11)", isNullable: false)]
        public int YearOfPassing
        {
            get { return data.year_of_passing; }
            set { data.year_of_passing = value; }
        }

        [ColumnInfo("class_per", "varchar(140)", isNullable: true)]
        public string? ClassPer
        {
            get { return data.class_per; }
            set { data.class_per = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("maj_opt_subj", "text", isNullable: true)]
        public string? MajOptSubj
        {
            get { return data.maj_opt_subj; }
            set { data.maj_opt_subj = value; }
        }

        [ColumnInfo("parent", "varchar(140)", isNullable: true)]
        public string? Parent
        {
            get { return data.parent; }
            set { data.parent = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("parentfield", "varchar(140)", isNullable: true)]
        public string? Parentfield
        {
            get { return data.parentfield; }
            set { data.parentfield = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("parenttype", "varchar(140)", isNullable: true)]
        public string? Parenttype
        {
            get { return data.parenttype; }
            set { data.parenttype = ERPNextConverter.TruncateString(value, 140); }
        }


    }
}

