/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Stock.PriceListCountry
{
    public class Stock_PriceListCountry_Service : SubServiceBase<ERP_Stock_PriceListCountry>
    {
        public Stock_PriceListCountry_Service(ERPNextClient client) : base(_DockType.Stock_PriceListCountry, client) { }

        protected override ERP_Stock_PriceListCountry FromERPObject(ERPObject obj)
        {
            return new ERP_Stock_PriceListCountry(obj);
        }

        /* custom functions can be added here */

    }
}

