/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Utilities.SMSLog
{
    public partial class ERP_Utilities_SMSLog : ERPNextObjectBase
    {
        public ERP_Utilities_SMSLog() : this(new ERPObject(_DockType.Utilities_SMSLog)) { }
        public ERP_Utilities_SMSLog(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Utilities_SMSLog>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("sender_name")]
        public string? SenderName
        {
            get { return data.sender_name; }
            set { data.sender_name = value; }
        }

        [Column("sent_on")]
        public DateOnly? SentOn
        {
            get { return data.sent_on; }
            set { data.sent_on = value; }
        }

        [Column("message")]
        public string? Message
        {
            get { return data.message; }
            set { data.message = value; }
        }

        [Column("no_of_requested_sms")]
        public int NoOfRequestedSms
        {
            get { return data.no_of_requested_sms; }
            set { data.no_of_requested_sms = value; }
        }

        [Column("requested_numbers")]
        public string? RequestedNumbers
        {
            get { return data.requested_numbers; }
            set { data.requested_numbers = value; }
        }

        [Column("no_of_sent_sms")]
        public int NoOfSentSms
        {
            get { return data.no_of_sent_sms; }
            set { data.no_of_sent_sms = value; }
        }

        [Column("sent_to")]
        public string? SentTo
        {
            get { return data.sent_to; }
            set { data.sent_to = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

