/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Integrations.WebhookData
{
    public class Integrations_WebhookData_Service : SubServiceBase<ERP_Integrations_WebhookData>
    {
        public Integrations_WebhookData_Service(ERPNextClient client) : base(_DockType.Integrations_WebhookData, client) { }

        protected override ERP_Integrations_WebhookData FromERPObject(ERPObject obj)
        {
            return new ERP_Integrations_WebhookData(obj);
        }

        /* custom functions can be added here */

    }
}

