/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Email.Notification
{
    public class Email_Notification_Service : SubServiceBase<ERP_Email_Notification>
    {
        public Email_Notification_Service(ERPNextClient client) : base(_DockType.Email_Notification, client) { }

        protected override ERP_Email_Notification FromERPObject(ERPObject obj)
        {
            return new ERP_Email_Notification(obj);
        }

        /* custom functions can be added here */

    }
}

