/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Buying.RequestforQuotationItem
{
    public class Buying_RequestforQuotationItem_Service : SubServiceBase<ERP_Buying_RequestforQuotationItem>
    {
        public Buying_RequestforQuotationItem_Service(ERPNextClient client) : base(_DockType.Buying_RequestforQuotationItem, client) { }

        protected override ERP_Buying_RequestforQuotationItem FromERPObject(ERPObject obj)
        {
            return new ERP_Buying_RequestforQuotationItem(obj);
        }

        /* custom functions can be added here */

    }
}

