/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Accounts.CostCenterAllocationPercentage
{
    public class Accounts_CostCenterAllocationPercentage_Service : SubServiceBase<ERP_Accounts_CostCenterAllocationPercentage>
    {
        public Accounts_CostCenterAllocationPercentage_Service(ERPNextClient client) : base(_DockType.Accounts_CostCenterAllocationPercentage, client) { }

        protected override ERP_Accounts_CostCenterAllocationPercentage FromERPObject(ERPObject obj)
        {
            return new ERP_Accounts_CostCenterAllocationPercentage(obj);
        }

        /* custom functions can be added here */

    }
}

