/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Selling.SalesOrder
{
    public partial class ERP_Selling_SalesOrder : ERPNextObjectBase
    {
        public ERP_Selling_SalesOrder() : this(new ERPObject(_DockType.Selling_SalesOrder)) { }
        public ERP_Selling_SalesOrder(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Selling_SalesOrder>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("title")]
        public string? Title
        {
            get { return data.title; }
            set { data.title = value; }
        }

        [Column("naming_series")]
        public string? NamingSeries
        {
            get { return data.naming_series; }
            set { data.naming_series = value; }
        }

        [Column("customer")]
        public string? Customer
        {
            get { return data.customer; }
            set { data.customer = value; }
        }

        [Column("customer_name")]
        public string? CustomerName
        {
            get { return data.customer_name; }
            set { data.customer_name = value; }
        }

        [Column("order_type")]
        public string? OrderType
        {
            get { return data.order_type; }
            set { data.order_type = value; }
        }

        [Column("skip_delivery_note")]
        public int SkipDeliveryNote
        {
            get { return data.skip_delivery_note; }
            set { data.skip_delivery_note = value; }
        }

        [Column("amended_from")]
        public string? AmendedFrom
        {
            get { return data.amended_from; }
            set { data.amended_from = value; }
        }

        [Column("company")]
        public string? Company
        {
            get { return data.company; }
            set { data.company = value; }
        }

        [Column("transaction_date")]
        public DateOnly? TransactionDate
        {
            get { return data.transaction_date; }
            set { data.transaction_date = value; }
        }

        [Column("delivery_date")]
        public DateOnly? DeliveryDate
        {
            get { return data.delivery_date; }
            set { data.delivery_date = value; }
        }

        [Column("po_no")]
        public string? PoNo
        {
            get { return data.po_no; }
            set { data.po_no = value; }
        }

        [Column("po_date")]
        public DateOnly? PoDate
        {
            get { return data.po_date; }
            set { data.po_date = value; }
        }

        [Column("tax_id")]
        public string? TaxId
        {
            get { return data.tax_id; }
            set { data.tax_id = value; }
        }

        [Column("cost_center")]
        public string? CostCenter
        {
            get { return data.cost_center; }
            set { data.cost_center = value; }
        }

        [Column("project")]
        public string? Project
        {
            get { return data.project; }
            set { data.project = value; }
        }

        [Column("customer_address")]
        public string? CustomerAddress
        {
            get { return data.customer_address; }
            set { data.customer_address = value; }
        }

        [Column("address_display")]
        public string? AddressDisplay
        {
            get { return data.address_display; }
            set { data.address_display = value; }
        }

        [Column("contact_person")]
        public string? ContactPerson
        {
            get { return data.contact_person; }
            set { data.contact_person = value; }
        }

        [Column("contact_display")]
        public string? ContactDisplay
        {
            get { return data.contact_display; }
            set { data.contact_display = value; }
        }

        [Column("contact_phone")]
        public string? ContactPhone
        {
            get { return data.contact_phone; }
            set { data.contact_phone = value; }
        }

        [Column("contact_mobile")]
        public string? ContactMobile
        {
            get { return data.contact_mobile; }
            set { data.contact_mobile = value; }
        }

        [Column("contact_email")]
        public string? ContactEmail
        {
            get { return data.contact_email; }
            set { data.contact_email = value; }
        }

        [Column("company_address")]
        public string? CompanyAddress
        {
            get { return data.company_address; }
            set { data.company_address = value; }
        }

        [Column("company_address_display")]
        public string? CompanyAddressDisplay
        {
            get { return data.company_address_display; }
            set { data.company_address_display = value; }
        }

        [Column("shipping_address_name")]
        public string? ShippingAddressName
        {
            get { return data.shipping_address_name; }
            set { data.shipping_address_name = value; }
        }

        [Column("shipping_address")]
        public string? ShippingAddress
        {
            get { return data.shipping_address; }
            set { data.shipping_address = value; }
        }

        [Column("dispatch_address_name")]
        public string? DispatchAddressName
        {
            get { return data.dispatch_address_name; }
            set { data.dispatch_address_name = value; }
        }

        [Column("dispatch_address")]
        public string? DispatchAddress
        {
            get { return data.dispatch_address; }
            set { data.dispatch_address = value; }
        }

        [Column("customer_group")]
        public string? CustomerGroup
        {
            get { return data.customer_group; }
            set { data.customer_group = value; }
        }

        [Column("territory")]
        public string? Territory
        {
            get { return data.territory; }
            set { data.territory = value; }
        }

        [Column("currency")]
        public string? Currency
        {
            get { return data.currency; }
            set { data.currency = value; }
        }

        [Column("conversion_rate")]
        public decimal ConversionRate
        {
            get { return data.conversion_rate; }
            set { data.conversion_rate = value; }
        }

        [Column("selling_price_list")]
        public string? SellingPriceList
        {
            get { return data.selling_price_list; }
            set { data.selling_price_list = value; }
        }

        [Column("price_list_currency")]
        public string? PriceListCurrency
        {
            get { return data.price_list_currency; }
            set { data.price_list_currency = value; }
        }

        [Column("plc_conversion_rate")]
        public decimal PlcConversionRate
        {
            get { return data.plc_conversion_rate; }
            set { data.plc_conversion_rate = value; }
        }

        [Column("ignore_pricing_rule")]
        public int IgnorePricingRule
        {
            get { return data.ignore_pricing_rule; }
            set { data.ignore_pricing_rule = value; }
        }

        [Column("set_warehouse")]
        public string? SetWarehouse
        {
            get { return data.set_warehouse; }
            set { data.set_warehouse = value; }
        }

        [Column("scan_barcode")]
        public string? ScanBarcode
        {
            get { return data.scan_barcode; }
            set { data.scan_barcode = value; }
        }

        [Column("total_qty")]
        public decimal TotalQty
        {
            get { return data.total_qty; }
            set { data.total_qty = value; }
        }

        [Column("base_total")]
        public decimal BaseTotal
        {
            get { return data.base_total; }
            set { data.base_total = value; }
        }

        [Column("base_net_total")]
        public decimal BaseNetTotal
        {
            get { return data.base_net_total; }
            set { data.base_net_total = value; }
        }

        [Column("total_net_weight")]
        public decimal TotalNetWeight
        {
            get { return data.total_net_weight; }
            set { data.total_net_weight = value; }
        }

        [Column("total")]
        public decimal Total
        {
            get { return data.total; }
            set { data.total = value; }
        }

        [Column("net_total")]
        public decimal NetTotal
        {
            get { return data.net_total; }
            set { data.net_total = value; }
        }

        [Column("tax_category")]
        public string? TaxCategory
        {
            get { return data.tax_category; }
            set { data.tax_category = value; }
        }

        [Column("shipping_rule")]
        public string? ShippingRule
        {
            get { return data.shipping_rule; }
            set { data.shipping_rule = value; }
        }

        [Column("taxes_and_charges")]
        public string? TaxesAndCharges
        {
            get { return data.taxes_and_charges; }
            set { data.taxes_and_charges = value; }
        }

        [Column("other_charges_calculation")]
        public string? OtherChargesCalculation
        {
            get { return data.other_charges_calculation; }
            set { data.other_charges_calculation = value; }
        }

        [Column("base_total_taxes_and_charges")]
        public decimal BaseTotalTaxesAndCharges
        {
            get { return data.base_total_taxes_and_charges; }
            set { data.base_total_taxes_and_charges = value; }
        }

        [Column("total_taxes_and_charges")]
        public decimal TotalTaxesAndCharges
        {
            get { return data.total_taxes_and_charges; }
            set { data.total_taxes_and_charges = value; }
        }

        [Column("loyalty_points")]
        public int LoyaltyPoints
        {
            get { return data.loyalty_points; }
            set { data.loyalty_points = value; }
        }

        [Column("loyalty_amount")]
        public decimal LoyaltyAmount
        {
            get { return data.loyalty_amount; }
            set { data.loyalty_amount = value; }
        }

        [Column("coupon_code")]
        public string? CouponCode
        {
            get { return data.coupon_code; }
            set { data.coupon_code = value; }
        }

        [Column("apply_discount_on")]
        public string? ApplyDiscountOn
        {
            get { return data.apply_discount_on; }
            set { data.apply_discount_on = value; }
        }

        [Column("base_discount_amount")]
        public decimal BaseDiscountAmount
        {
            get { return data.base_discount_amount; }
            set { data.base_discount_amount = value; }
        }

        [Column("additional_discount_percentage")]
        public decimal AdditionalDiscountPercentage
        {
            get { return data.additional_discount_percentage; }
            set { data.additional_discount_percentage = value; }
        }

        [Column("discount_amount")]
        public decimal DiscountAmount
        {
            get { return data.discount_amount; }
            set { data.discount_amount = value; }
        }

        [Column("base_grand_total")]
        public decimal BaseGrandTotal
        {
            get { return data.base_grand_total; }
            set { data.base_grand_total = value; }
        }

        [Column("base_rounding_adjustment")]
        public decimal BaseRoundingAdjustment
        {
            get { return data.base_rounding_adjustment; }
            set { data.base_rounding_adjustment = value; }
        }

        [Column("base_rounded_total")]
        public decimal BaseRoundedTotal
        {
            get { return data.base_rounded_total; }
            set { data.base_rounded_total = value; }
        }

        [Column("base_in_words")]
        public string? BaseInWords
        {
            get { return data.base_in_words; }
            set { data.base_in_words = value; }
        }

        [Column("grand_total")]
        public decimal GrandTotal
        {
            get { return data.grand_total; }
            set { data.grand_total = value; }
        }

        [Column("rounding_adjustment")]
        public decimal RoundingAdjustment
        {
            get { return data.rounding_adjustment; }
            set { data.rounding_adjustment = value; }
        }

        [Column("rounded_total")]
        public decimal RoundedTotal
        {
            get { return data.rounded_total; }
            set { data.rounded_total = value; }
        }

        [Column("in_words")]
        public string? InWords
        {
            get { return data.in_words; }
            set { data.in_words = value; }
        }

        [Column("advance_paid")]
        public decimal AdvancePaid
        {
            get { return data.advance_paid; }
            set { data.advance_paid = value; }
        }

        [Column("disable_rounded_total")]
        public int DisableRoundedTotal
        {
            get { return data.disable_rounded_total; }
            set { data.disable_rounded_total = value; }
        }

        [Column("payment_terms_template")]
        public string? PaymentTermsTemplate
        {
            get { return data.payment_terms_template; }
            set { data.payment_terms_template = value; }
        }

        [Column("tc_name")]
        public string? TcName
        {
            get { return data.tc_name; }
            set { data.tc_name = value; }
        }

        [Column("terms")]
        public string? Terms
        {
            get { return data.terms; }
            set { data.terms = value; }
        }

        [Column("is_internal_customer")]
        public int IsInternalCustomer
        {
            get { return data.is_internal_customer; }
            set { data.is_internal_customer = value; }
        }

        [Column("represents_company")]
        public string? RepresentsCompany
        {
            get { return data.represents_company; }
            set { data.represents_company = value; }
        }

        [Column("inter_company_order_reference")]
        public string? InterCompanyOrderReference
        {
            get { return data.inter_company_order_reference; }
            set { data.inter_company_order_reference = value; }
        }

        [Column("party_account_currency")]
        public string? PartyAccountCurrency
        {
            get { return data.party_account_currency; }
            set { data.party_account_currency = value; }
        }

        [Column("source")]
        public string? Source
        {
            get { return data.source; }
            set { data.source = value; }
        }

        [Column("campaign")]
        public string? Campaign
        {
            get { return data.campaign; }
            set { data.campaign = value; }
        }

        [Column("language")]
        public string? Language
        {
            get { return data.language; }
            set { data.language = value; }
        }

        [Column("letter_head")]
        public string? LetterHead
        {
            get { return data.letter_head; }
            set { data.letter_head = value; }
        }

        [Column("select_print_heading")]
        public string? SelectPrintHeading
        {
            get { return data.select_print_heading; }
            set { data.select_print_heading = value; }
        }

        [Column("group_same_items")]
        public int GroupSameItems
        {
            get { return data.group_same_items; }
            set { data.group_same_items = value; }
        }

        [Column("status")]
        public string? Status
        {
            get { return data.status; }
            set { data.status = value; }
        }

        [Column("delivery_status")]
        public string? DeliveryStatus
        {
            get { return data.delivery_status; }
            set { data.delivery_status = value; }
        }

        [Column("per_delivered")]
        public decimal PerDelivered
        {
            get { return data.per_delivered; }
            set { data.per_delivered = value; }
        }

        [Column("per_billed")]
        public decimal PerBilled
        {
            get { return data.per_billed; }
            set { data.per_billed = value; }
        }

        [Column("per_picked")]
        public decimal PerPicked
        {
            get { return data.per_picked; }
            set { data.per_picked = value; }
        }

        [Column("billing_status")]
        public string? BillingStatus
        {
            get { return data.billing_status; }
            set { data.billing_status = value; }
        }

        [Column("sales_partner")]
        public string? SalesPartner
        {
            get { return data.sales_partner; }
            set { data.sales_partner = value; }
        }

        [Column("amount_eligible_for_commission")]
        public decimal AmountEligibleForCommission
        {
            get { return data.amount_eligible_for_commission; }
            set { data.amount_eligible_for_commission = value; }
        }

        [Column("commission_rate")]
        public decimal CommissionRate
        {
            get { return data.commission_rate; }
            set { data.commission_rate = value; }
        }

        [Column("total_commission")]
        public decimal TotalCommission
        {
            get { return data.total_commission; }
            set { data.total_commission = value; }
        }

        [Column("from_date")]
        public DateOnly? FromDate
        {
            get { return data.from_date; }
            set { data.from_date = value; }
        }

        [Column("to_date")]
        public DateOnly? ToDate
        {
            get { return data.to_date; }
            set { data.to_date = value; }
        }

        [Column("auto_repeat")]
        public string? AutoRepeat
        {
            get { return data.auto_repeat; }
            set { data.auto_repeat = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }

        [Column("_seen")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Seen
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._seen; }
            set { data._seen = value; }
        }

        [Column("exempt_from_sales_tax")]
        public int ExemptFromSalesTax
        {
            get { return data.exempt_from_sales_tax; }
            set { data.exempt_from_sales_tax = value; }
        }


    }
}

