/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Printing.PrintFormat
{
    public partial class ERP_Printing_PrintFormat : ERPNextObjectBase
    {
        public ERP_Printing_PrintFormat() : this(new ERPObject(_DocType.Printing_PrintFormat)) { }
        public ERP_Printing_PrintFormat(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("doc_type", "varchar(140)", isNullable: true)]
        public string? DocType
        {
            get { return data.doc_type; }
            set { data.doc_type = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("module", "varchar(140)", isNullable: true)]
        public string? Module
        {
            get { return data.module; }
            set { data.module = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("default_print_language", "varchar(140)", isNullable: true)]
        public string? DefaultPrintLanguage
        {
            get { return data.default_print_language; }
            set { data.default_print_language = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("standard", "varchar(140)", isNullable: true)]
        public string? Standard
        {
            get { return data.standard; }
            set { data.standard = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("custom_format", "int(1)", isNullable: false)]
        public bool CustomFormat
        {
            get { return ERPNextConverter.IntToBool((int)data.custom_format); }
            set { data.custom_format = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("disabled", "int(1)", isNullable: false)]
        public bool Disabled
        {
            get { return ERPNextConverter.IntToBool((int)data.disabled); }
            set { data.disabled = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("print_format_type", "varchar(140)", isNullable: true)]
        public string? PrintFormatType
        {
            get { return data.print_format_type; }
            set { data.print_format_type = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("raw_printing", "int(1)", isNullable: false)]
        public bool RawPrinting
        {
            get { return ERPNextConverter.IntToBool((int)data.raw_printing); }
            set { data.raw_printing = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("html", "longtext", isNullable: true)]
        public string? Html
        {
            get { return data.html; }
            set { data.html = value; }
        }

        [ColumnInfo("raw_commands", "longtext", isNullable: true)]
        public string? RawCommands
        {
            get { return data.raw_commands; }
            set { data.raw_commands = value; }
        }

        [ColumnInfo("margin_top", "decimal(21,9)", isNullable: false)]
        public decimal MarginTop
        {
            get { return data.margin_top; }
            set { data.margin_top = value; }
        }

        [ColumnInfo("margin_bottom", "decimal(21,9)", isNullable: false)]
        public decimal MarginBottom
        {
            get { return data.margin_bottom; }
            set { data.margin_bottom = value; }
        }

        [ColumnInfo("margin_left", "decimal(21,9)", isNullable: false)]
        public decimal MarginLeft
        {
            get { return data.margin_left; }
            set { data.margin_left = value; }
        }

        [ColumnInfo("margin_right", "decimal(21,9)", isNullable: false)]
        public decimal MarginRight
        {
            get { return data.margin_right; }
            set { data.margin_right = value; }
        }

        [ColumnInfo("align_labels_right", "int(1)", isNullable: false)]
        public bool AlignLabelsRight
        {
            get { return ERPNextConverter.IntToBool((int)data.align_labels_right); }
            set { data.align_labels_right = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("show_section_headings", "int(1)", isNullable: false)]
        public bool ShowSectionHeadings
        {
            get { return ERPNextConverter.IntToBool((int)data.show_section_headings); }
            set { data.show_section_headings = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("line_breaks", "int(1)", isNullable: false)]
        public bool LineBreaks
        {
            get { return ERPNextConverter.IntToBool((int)data.line_breaks); }
            set { data.line_breaks = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("absolute_value", "int(1)", isNullable: false)]
        public bool AbsoluteValue
        {
            get { return ERPNextConverter.IntToBool((int)data.absolute_value); }
            set { data.absolute_value = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("font_size", "int(11)", isNullable: false)]
        public int FontSize
        {
            get { return data.font_size; }
            set { data.font_size = value; }
        }

        [ColumnInfo("font", "varchar(140)", isNullable: true)]
        public string? Font
        {
            get { return data.font; }
            set { data.font = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("page_number", "varchar(140)", isNullable: true)]
        public string? PageNumber
        {
            get { return data.page_number; }
            set { data.page_number = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("css", "longtext", isNullable: true)]
        public string? Css
        {
            get { return data.css; }
            set { data.css = value; }
        }

        [ColumnInfo("format_data", "longtext", isNullable: true)]
        public string? FormatData
        {
            get { return data.format_data; }
            set { data.format_data = value; }
        }

        [ColumnInfo("print_format_builder", "int(1)", isNullable: false)]
        public bool PrintFormatBuilder
        {
            get { return ERPNextConverter.IntToBool((int)data.print_format_builder); }
            set { data.print_format_builder = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("print_format_builder_beta", "int(1)", isNullable: false)]
        public bool PrintFormatBuilderBeta
        {
            get { return ERPNextConverter.IntToBool((int)data.print_format_builder_beta); }
            set { data.print_format_builder_beta = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("_user_tags", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [ColumnInfo("_comments", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [ColumnInfo("_assign", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [ColumnInfo("_liked_by", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

