/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.EventStreaming.DocumentTypeFieldMapping
{
    public partial class ERP_EventStreaming_DocumentTypeFieldMapping : ERPNextObjectBase
    {
        public ERP_EventStreaming_DocumentTypeFieldMapping() : this(new ERPObject(_DockType.EventStreaming_DocumentTypeFieldMapping)) { }
        public ERP_EventStreaming_DocumentTypeFieldMapping(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_EventStreaming_DocumentTypeFieldMapping>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("local_fieldname")]
        public string? LocalFieldname
        {
            get { return data.local_fieldname; }
            set { data.local_fieldname = value; }
        }

        [Column("mapping_type")]
        public string? MappingType
        {
            get { return data.mapping_type; }
            set { data.mapping_type = value; }
        }

        [Column("mapping")]
        public string? Mapping
        {
            get { return data.mapping; }
            set { data.mapping = value; }
        }

        [Column("remote_value_filters")]
        public string? RemoteValueFilters
        {
            get { return data.remote_value_filters; }
            set { data.remote_value_filters = value; }
        }

        [Column("remote_fieldname")]
        public string? RemoteFieldname
        {
            get { return data.remote_fieldname; }
            set { data.remote_fieldname = value; }
        }

        [Column("default_value")]
        public string? DefaultValue
        {
            get { return data.default_value; }
            set { data.default_value = value; }
        }

        [Column("parent")]
        public string? Parent
        {
            get { return data.parent; }
            set { data.parent = value; }
        }

        [Column("parentfield")]
        public string? Parentfield
        {
            get { return data.parentfield; }
            set { data.parentfield = value; }
        }

        [Column("parenttype")]
        public string? Parenttype
        {
            get { return data.parenttype; }
            set { data.parenttype = value; }
        }


    }
}

