/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.CRM.Lead
{
    public partial class ERP_CRM_Lead : ERPNextObjectBase
    {
        public ERP_CRM_Lead() : this(new ERPObject(_DockType.CRM_Lead)) { }
        public ERP_CRM_Lead(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_CRM_Lead>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("naming_series")]
        public string? NamingSeries
        {
            get { return data.naming_series; }
            set { data.naming_series = value; }
        }

        [Column("salutation")]
        public string? Salutation
        {
            get { return data.salutation; }
            set { data.salutation = value; }
        }

        [Column("first_name")]
        public string? FirstName
        {
            get { return data.first_name; }
            set { data.first_name = value; }
        }

        [Column("middle_name")]
        public string? MiddleName
        {
            get { return data.middle_name; }
            set { data.middle_name = value; }
        }

        [Column("last_name")]
        public string? LastName
        {
            get { return data.last_name; }
            set { data.last_name = value; }
        }

        [Column("lead_name")]
        public string? LeadName
        {
            get { return data.lead_name; }
            set { data.lead_name = value; }
        }

        [Column("job_title")]
        public string? JobTitle
        {
            get { return data.job_title; }
            set { data.job_title = value; }
        }

        [Column("gender")]
        public string? Gender
        {
            get { return data.gender; }
            set { data.gender = value; }
        }

        [Column("source")]
        public string? Source
        {
            get { return data.source; }
            set { data.source = value; }
        }

        [Column("lead_owner")]
        public string? LeadOwner
        {
            get { return data.lead_owner; }
            set { data.lead_owner = value; }
        }

        [Column("status")]
        public string? Status
        {
            get { return data.status; }
            set { data.status = value; }
        }

        [Column("customer")]
        public string? Customer
        {
            get { return data.customer; }
            set { data.customer = value; }
        }

        [Column("type")]
        public string? Type
        {
            get { return data.type; }
            set { data.type = value; }
        }

        [Column("request_type")]
        public string? RequestType
        {
            get { return data.request_type; }
            set { data.request_type = value; }
        }

        [Column("email_id")]
        public string? EmailId
        {
            get { return data.email_id; }
            set { data.email_id = value; }
        }

        [Column("website")]
        public string? Website
        {
            get { return data.website; }
            set { data.website = value; }
        }

        [Column("mobile_no")]
        public string? MobileNo
        {
            get { return data.mobile_no; }
            set { data.mobile_no = value; }
        }

        [Column("whatsapp_no")]
        public string? WhatsappNo
        {
            get { return data.whatsapp_no; }
            set { data.whatsapp_no = value; }
        }

        [Column("phone")]
        public string? Phone
        {
            get { return data.phone; }
            set { data.phone = value; }
        }

        [Column("phone_ext")]
        public string? PhoneExt
        {
            get { return data.phone_ext; }
            set { data.phone_ext = value; }
        }

        [Column("company_name")]
        public string? CompanyName
        {
            get { return data.company_name; }
            set { data.company_name = value; }
        }

        [Column("no_of_employees")]
        public string? NoOfEmployees
        {
            get { return data.no_of_employees; }
            set { data.no_of_employees = value; }
        }

        [Column("annual_revenue")]
        public decimal AnnualRevenue
        {
            get { return data.annual_revenue; }
            set { data.annual_revenue = value; }
        }

        [Column("industry")]
        public string? Industry
        {
            get { return data.industry; }
            set { data.industry = value; }
        }

        [Column("market_segment")]
        public string? MarketSegment
        {
            get { return data.market_segment; }
            set { data.market_segment = value; }
        }

        [Column("territory")]
        public string? Territory
        {
            get { return data.territory; }
            set { data.territory = value; }
        }

        [Column("fax")]
        public string? Fax
        {
            get { return data.fax; }
            set { data.fax = value; }
        }

        [Column("city")]
        public string? City
        {
            get { return data.city; }
            set { data.city = value; }
        }

        [Column("state")]
        public string? State
        {
            get { return data.state; }
            set { data.state = value; }
        }

        [Column("country")]
        public string? Country
        {
            get { return data.country; }
            set { data.country = value; }
        }

        [Column("qualification_status")]
        public string? QualificationStatus
        {
            get { return data.qualification_status; }
            set { data.qualification_status = value; }
        }

        [Column("qualified_by")]
        public string? QualifiedBy
        {
            get { return data.qualified_by; }
            set { data.qualified_by = value; }
        }

        [Column("qualified_on")]
        public DateOnly? QualifiedOn
        {
            get { return data.qualified_on; }
            set { data.qualified_on = value; }
        }

        [Column("campaign_name")]
        public string? CampaignName
        {
            get { return data.campaign_name; }
            set { data.campaign_name = value; }
        }

        [Column("company")]
        public string? Company
        {
            get { return data.company; }
            set { data.company = value; }
        }

        [Column("language")]
        public string? Language
        {
            get { return data.language; }
            set { data.language = value; }
        }

        [Column("image")]
        public string? Image
        {
            get { return data.image; }
            set { data.image = value; }
        }

        [Column("title")]
        public string? Title
        {
            get { return data.title; }
            set { data.title = value; }
        }

        [Column("disabled")]
        public int Disabled
        {
            get { return data.disabled; }
            set { data.disabled = value; }
        }

        [Column("unsubscribed")]
        public int Unsubscribed
        {
            get { return data.unsubscribed; }
            set { data.unsubscribed = value; }
        }

        [Column("blog_subscriber")]
        public int BlogSubscriber
        {
            get { return data.blog_subscriber; }
            set { data.blog_subscriber = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

