/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Setup.AuthorizationRule
{
    public partial class ERP_Setup_AuthorizationRule : ERPNextObjectBase
    {
        public ERP_Setup_AuthorizationRule() : this(new ERPObject(_DocType.Setup_AuthorizationRule)) { }
        public ERP_Setup_AuthorizationRule(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("transaction", "varchar(140)", isNullable: true)]
        public string? Transaction
        {
            get { return data.transaction; }
            set { data.transaction = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("based_on", "varchar(140)", isNullable: true)]
        public string? BasedOn
        {
            get { return data.based_on; }
            set { data.based_on = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("customer_or_item", "varchar(140)", isNullable: true)]
        public string? CustomerOrItem
        {
            get { return data.customer_or_item; }
            set { data.customer_or_item = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("master_name", "varchar(140)", isNullable: true)]
        public string? MasterName
        {
            get { return data.master_name; }
            set { data.master_name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("company", "varchar(140)", isNullable: true)]
        public string? Company
        {
            get { return data.company; }
            set { data.company = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("@value", "decimal(21,9)", isNullable: false)]
        public decimal Value
        {
            get { return data.@value; }
            set { data.@value = value; }
        }

        [ColumnInfo("system_role", "varchar(140)", isNullable: true)]
        public string? SystemRole
        {
            get { return data.system_role; }
            set { data.system_role = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("to_emp", "varchar(140)", isNullable: true)]
        public string? ToEmp
        {
            get { return data.to_emp; }
            set { data.to_emp = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("system_user", "varchar(140)", isNullable: true)]
        public string? SystemUser
        {
            get { return data.system_user; }
            set { data.system_user = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("to_designation", "varchar(140)", isNullable: true)]
        public string? ToDesignation
        {
            get { return data.to_designation; }
            set { data.to_designation = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("approving_role", "varchar(140)", isNullable: true)]
        public string? ApprovingRole
        {
            get { return data.approving_role; }
            set { data.approving_role = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("approving_user", "varchar(140)", isNullable: true)]
        public string? ApprovingUser
        {
            get { return data.approving_user; }
            set { data.approving_user = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("_user_tags", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [ColumnInfo("_comments", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [ColumnInfo("_assign", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [ColumnInfo("_liked_by", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

