/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Website.BlogPost
{
    public partial class ERP_Website_BlogPost : ERPNextObjectBase
    {
        public ERP_Website_BlogPost() : this(new ERPObject(_DocType.Website_BlogPost)) { }
        public ERP_Website_BlogPost(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("title", "varchar(140)", isNullable: true)]
        public string? Title
        {
            get { return data.title; }
            set { data.title = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("blog_category", "varchar(140)", isNullable: true)]
        public string? BlogCategory
        {
            get { return data.blog_category; }
            set { data.blog_category = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("blogger", "varchar(140)", isNullable: true)]
        public string? Blogger
        {
            get { return data.blogger; }
            set { data.blogger = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("route", "varchar(140)", isNullable: true)]
        public string? Route
        {
            get { return data.route; }
            set { data.route = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("read_time", "int(11)", isNullable: false)]
        public int ReadTime
        {
            get { return data.read_time; }
            set { data.read_time = value; }
        }

        [ColumnInfo("published_on", "date", isNullable: true)]
        public DateOnly? PublishedOn
        {
            get { return ERPNextConverter.StringToDateOnly(data.published_on); }
            set { data.published_on = ERPNextConverter.DateOnlyToString(value); }
        }

        [ColumnInfo("published", "int(1)", isNullable: false)]
        public bool Published
        {
            get { return ERPNextConverter.IntToBool((int)data.published); }
            set { data.published = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("featured", "int(1)", isNullable: false)]
        public bool Featured
        {
            get { return ERPNextConverter.IntToBool((int)data.featured); }
            set { data.featured = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("hide_cta", "int(1)", isNullable: false)]
        public bool HideCta
        {
            get { return ERPNextConverter.IntToBool((int)data.hide_cta); }
            set { data.hide_cta = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("enable_email_notification", "int(1)", isNullable: false)]
        public bool EnableEmailNotification
        {
            get { return ERPNextConverter.IntToBool((int)data.enable_email_notification); }
            set { data.enable_email_notification = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("disable_comments", "int(1)", isNullable: false)]
        public bool DisableComments
        {
            get { return ERPNextConverter.IntToBool((int)data.disable_comments); }
            set { data.disable_comments = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("disable_likes", "int(1)", isNullable: false)]
        public bool DisableLikes
        {
            get { return ERPNextConverter.IntToBool((int)data.disable_likes); }
            set { data.disable_likes = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("blog_intro", "text", isNullable: true)]
        public string? BlogIntro
        {
            get { return data.blog_intro; }
            set { data.blog_intro = value; }
        }

        [ColumnInfo("content_type", "varchar(140)", isNullable: true)]
        public string? ContentType
        {
            get { return data.content_type; }
            set { data.content_type = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("content", "longtext", isNullable: true)]
        public string? Content
        {
            get { return data.content; }
            set { data.content = value; }
        }

        [ColumnInfo("content_md", "longtext", isNullable: true)]
        public string? ContentMd
        {
            get { return data.content_md; }
            set { data.content_md = value; }
        }

        [ColumnInfo("content_html", "longtext", isNullable: true)]
        public string? ContentHtml
        {
            get { return data.content_html; }
            set { data.content_html = value; }
        }

        [ColumnInfo("email_sent", "int(1)", isNullable: false)]
        public bool EmailSent
        {
            get { return ERPNextConverter.IntToBool((int)data.email_sent); }
            set { data.email_sent = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("meta_title", "varchar(60)", isNullable: true)]
        public string? MetaTitle
        {
            get { return data.meta_title; }
            set { data.meta_title = ERPNextConverter.TruncateString(value, 60); }
        }

        [ColumnInfo("meta_description", "text", isNullable: true)]
        public string? MetaDescription
        {
            get { return data.meta_description; }
            set { data.meta_description = value; }
        }

        [ColumnInfo("meta_image", "text", isNullable: true)]
        public string? MetaImage
        {
            get { return data.meta_image; }
            set { data.meta_image = value; }
        }

        [ColumnInfo("_user_tags", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [ColumnInfo("_comments", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [ColumnInfo("_assign", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [ColumnInfo("_liked_by", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

