/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Assets.LinkedLocation
{
    public class Assets_LinkedLocation_Service : SubServiceBase<ERP_Assets_LinkedLocation>
    {
        public Assets_LinkedLocation_Service(ERPNextClient client) : base(_DockType.Assets_LinkedLocation, client) { }

        protected override ERP_Assets_LinkedLocation FromERPObject(ERPObject obj)
        {
            return new ERP_Assets_LinkedLocation(obj);
        }

        /* custom functions can be added here */

    }
}

