/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Regional.ProductTaxCategory
{
    public class Regional_ProductTaxCategory_Service : SubServiceBase<ERP_Regional_ProductTaxCategory>
    {
        public Regional_ProductTaxCategory_Service(ERPNextClient client) : base(_DockType.Regional_ProductTaxCategory, client) { }

        protected override ERP_Regional_ProductTaxCategory FromERPObject(ERPObject obj)
        {
            return new ERP_Regional_ProductTaxCategory(obj);
        }

        /* custom functions can be added here */

    }
}

