/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Integrations.OAuthClient
{
    public partial class ERP_Integrations_OAuthClient : ERPNextObjectBase
    {
        public ERP_Integrations_OAuthClient() : this(new ERPObject(_DockType.Integrations_OAuthClient)) { }
        public ERP_Integrations_OAuthClient(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Integrations_OAuthClient>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("client_id")]
        public string? ClientId
        {
            get { return data.client_id; }
            set { data.client_id = value; }
        }

        [Column("app_name")]
        public string? AppName
        {
            get { return data.app_name; }
            set { data.app_name = value; }
        }

        [Column("user")]
        public string? User
        {
            get { return data.user; }
            set { data.user = value; }
        }

        [Column("client_secret")]
        public string? ClientSecret
        {
            get { return data.client_secret; }
            set { data.client_secret = value; }
        }

        [Column("skip_authorization")]
        public int SkipAuthorization
        {
            get { return data.skip_authorization; }
            set { data.skip_authorization = value; }
        }

        [Column("scopes")]
        public string? Scopes
        {
            get { return data.scopes; }
            set { data.scopes = value; }
        }

        [Column("redirect_uris")]
        public string? RedirectUris
        {
            get { return data.redirect_uris; }
            set { data.redirect_uris = value; }
        }

        [Column("default_redirect_uri")]
        public string? DefaultRedirectUri
        {
            get { return data.default_redirect_uri; }
            set { data.default_redirect_uri = value; }
        }

        [Column("grant_type")]
        public string? GrantType
        {
            get { return data.grant_type; }
            set { data.grant_type = value; }
        }

        [Column("response_type")]
        public string? ResponseType
        {
            get { return data.response_type; }
            set { data.response_type = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

