/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Setup.Company
{
    public class Setup_Company_Service : SubServiceBase<ERP_Setup_Company>
    {
        public Setup_Company_Service(ERPNextClient client) : base(_DockType.Setup_Company, client) { }

        protected override ERP_Setup_Company FromERPObject(ERPObject obj)
        {
            return new ERP_Setup_Company(obj);
        }

        /* custom functions can be added here */

    }
}

