/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Setup.SalesPartner
{
    public class Setup_SalesPartner_Service : SubServiceBase<ERP_Setup_SalesPartner>
    {
        public Setup_SalesPartner_Service(ERPNextClient client) : base(_DockType.Setup_SalesPartner, client) { }

        protected override ERP_Setup_SalesPartner FromERPObject(ERPObject obj)
        {
            return new ERP_Setup_SalesPartner(obj);
        }

        /* custom functions can be added here */

    }
}

