/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Website.WebPageView
{
    public class Website_WebPageView_Service : SubServiceBase<ERP_Website_WebPageView>
    {
        public Website_WebPageView_Service(ERPNextClient client) : base(_DockType.Website_WebPageView, client) { }

        protected override ERP_Website_WebPageView FromERPObject(ERPObject obj)
        {
            return new ERP_Website_WebPageView(obj);
        }

        /* custom functions can be added here */

    }
}

