/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Core.File
{
    public class Core_File_Service : SubServiceBase<ERP_Core_File>
    {
        public Core_File_Service(ERPNextClient client) : base(_DockType.Core_File, client) { }

        protected override ERP_Core_File FromERPObject(ERPObject obj)
        {
            return new ERP_Core_File(obj);
        }

        /* custom functions can be added here */

    }
}

