/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Manufacturing.Workstation
{
    public partial class ERP_Manufacturing_Workstation : ERPNextObjectBase
    {
        public ERP_Manufacturing_Workstation() : this(new ERPObject(_DocType.Manufacturing_Workstation)) { }
        public ERP_Manufacturing_Workstation(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("workstation_name", "varchar(140)", isNullable: true)]
        public string? WorkstationName
        {
            get { return data.workstation_name; }
            set { data.workstation_name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("production_capacity", "int(11)", isNullable: false)]
        public int ProductionCapacity
        {
            get { return data.production_capacity; }
            set { data.production_capacity = value; }
        }

        [ColumnInfo("hour_rate_electricity", "decimal(21,9)", isNullable: false)]
        public decimal HourRateElectricity
        {
            get { return data.hour_rate_electricity; }
            set { data.hour_rate_electricity = value; }
        }

        [ColumnInfo("hour_rate_consumable", "decimal(21,9)", isNullable: false)]
        public decimal HourRateConsumable
        {
            get { return data.hour_rate_consumable; }
            set { data.hour_rate_consumable = value; }
        }

        [ColumnInfo("hour_rate_rent", "decimal(21,9)", isNullable: false)]
        public decimal HourRateRent
        {
            get { return data.hour_rate_rent; }
            set { data.hour_rate_rent = value; }
        }

        [ColumnInfo("hour_rate_labour", "decimal(21,9)", isNullable: false)]
        public decimal HourRateLabour
        {
            get { return data.hour_rate_labour; }
            set { data.hour_rate_labour = value; }
        }

        [ColumnInfo("hour_rate", "decimal(21,9)", isNullable: false)]
        public decimal HourRate
        {
            get { return data.hour_rate; }
            set { data.hour_rate = value; }
        }

        [ColumnInfo("holiday_list", "varchar(140)", isNullable: true)]
        public string? HolidayList
        {
            get { return data.holiday_list; }
            set { data.holiday_list = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("description", "text", isNullable: true)]
        public string? Description
        {
            get { return data.description; }
            set { data.description = value; }
        }

        [ColumnInfo("_user_tags", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [ColumnInfo("_comments", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [ColumnInfo("_assign", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [ColumnInfo("_liked_by", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

