/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Printing.LetterHead
{
    public partial class ERP_Printing_LetterHead : ERPNextObjectBase
    {
        public ERP_Printing_LetterHead() : this(new ERPObject(_DockType.Printing_LetterHead)) { }
        public ERP_Printing_LetterHead(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Printing_LetterHead>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("letter_head_name")]
        public string? LetterHeadName
        {
            get { return data.letter_head_name; }
            set { data.letter_head_name = value; }
        }

        [Column("source")]
        public string? Source
        {
            get { return data.source; }
            set { data.source = value; }
        }

        [Column("footer_source")]
        public string? FooterSource
        {
            get { return data.footer_source; }
            set { data.footer_source = value; }
        }

        [Column("disabled")]
        public int Disabled
        {
            get { return data.disabled; }
            set { data.disabled = value; }
        }

        [Column("is_default")]
        public int IsDefault
        {
            get { return data.is_default; }
            set { data.is_default = value; }
        }

        [Column("image")]
        public string? Image
        {
            get { return data.image; }
            set { data.image = value; }
        }

        [Column("image_height")]
        public decimal ImageHeight
        {
            get { return data.image_height; }
            set { data.image_height = value; }
        }

        [Column("image_width")]
        public decimal ImageWidth
        {
            get { return data.image_width; }
            set { data.image_width = value; }
        }

        [Column("align")]
        public string? Align
        {
            get { return data.align; }
            set { data.align = value; }
        }

        [Column("content")]
        public string? Content
        {
            get { return data.content; }
            set { data.content = value; }
        }

        [Column("footer")]
        public string? Footer
        {
            get { return data.footer; }
            set { data.footer = value; }
        }

        [Column("footer_image")]
        public string? FooterImage
        {
            get { return data.footer_image; }
            set { data.footer_image = value; }
        }

        [Column("footer_image_height")]
        public decimal FooterImageHeight
        {
            get { return data.footer_image_height; }
            set { data.footer_image_height = value; }
        }

        [Column("footer_image_width")]
        public decimal FooterImageWidth
        {
            get { return data.footer_image_width; }
            set { data.footer_image_width = value; }
        }

        [Column("footer_align")]
        public string? FooterAlign
        {
            get { return data.footer_align; }
            set { data.footer_align = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

