/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Website.PortalMenuItem
{
    public class Website_PortalMenuItem_Service : SubServiceBase<ERP_Website_PortalMenuItem>
    {
        public Website_PortalMenuItem_Service(ERPNextClient client) : base(_DockType.Website_PortalMenuItem, client) { }

        protected override ERP_Website_PortalMenuItem FromERPObject(ERPObject obj)
        {
            return new ERP_Website_PortalMenuItem(obj);
        }

        /* custom functions can be added here */

    }
}

