/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Workflow.WorkflowTransition
{
    public partial class ERP_Workflow_WorkflowTransition : ERPNextObjectBase
    {
        public ERP_Workflow_WorkflowTransition() : this(new ERPObject(_DocType.Workflow_WorkflowTransition)) { }
        public ERP_Workflow_WorkflowTransition(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("state", "varchar(140)", isNullable: true)]
        public string? State
        {
            get { return data.state; }
            set { data.state = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("action", "varchar(140)", isNullable: true)]
        public string? Action
        {
            get { return data.action; }
            set { data.action = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("next_state", "varchar(140)", isNullable: true)]
        public string? NextState
        {
            get { return data.next_state; }
            set { data.next_state = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("allowed", "varchar(140)", isNullable: true)]
        public string? Allowed
        {
            get { return data.allowed; }
            set { data.allowed = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("allow_self_approval", "int(1)", isNullable: false)]
        public bool AllowSelfApproval
        {
            get { return ERPNextConverter.IntToBool((int)data.allow_self_approval); }
            set { data.allow_self_approval = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("condition", "longtext", isNullable: true)]
        public string? Condition
        {
            get { return data.condition; }
            set { data.condition = value; }
        }

        [ColumnInfo("parent", "varchar(140)", isNullable: true)]
        public string? Parent
        {
            get { return data.parent; }
            set { data.parent = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("parentfield", "varchar(140)", isNullable: true)]
        public string? Parentfield
        {
            get { return data.parentfield; }
            set { data.parentfield = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("parenttype", "varchar(140)", isNullable: true)]
        public string? Parenttype
        {
            get { return data.parenttype; }
            set { data.parenttype = ERPNextConverter.TruncateString(value, 140); }
        }


    }
}

