/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Communication.CommunicationMediumTimeslot
{
    public class Communication_CommunicationMediumTimeslot_Service : SubServiceBase<ERP_Communication_CommunicationMediumTimeslot>
    {
        public Communication_CommunicationMediumTimeslot_Service(ERPNextClient client) : base(_DockType.Communication_CommunicationMediumTimeslot, client) { }

        protected override ERP_Communication_CommunicationMediumTimeslot FromERPObject(ERPObject obj)
        {
            return new ERP_Communication_CommunicationMediumTimeslot(obj);
        }

        /* custom functions can be added here */

    }
}

