/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Email.EmailDomain
{
    public partial class ERP_Email_EmailDomain : ERPNextObjectBase
    {
        public ERP_Email_EmailDomain() : this(new ERPObject(_DockType.Email_EmailDomain)) { }
        public ERP_Email_EmailDomain(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Email_EmailDomain>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("domain_name")]
        public string? DomainName
        {
            get { return data.domain_name; }
            set { data.domain_name = value; }
        }

        [Column("email_server")]
        public string? EmailServer
        {
            get { return data.email_server; }
            set { data.email_server = value; }
        }

        [Column("use_imap")]
        public int UseImap
        {
            get { return data.use_imap; }
            set { data.use_imap = value; }
        }

        [Column("use_ssl")]
        public int UseSsl
        {
            get { return data.use_ssl; }
            set { data.use_ssl = value; }
        }

        [Column("use_starttls")]
        public int UseStarttls
        {
            get { return data.use_starttls; }
            set { data.use_starttls = value; }
        }

        [Column("incoming_port")]
        public string? IncomingPort
        {
            get { return data.incoming_port; }
            set { data.incoming_port = value; }
        }

        [Column("attachment_limit")]
        public int AttachmentLimit
        {
            get { return data.attachment_limit; }
            set { data.attachment_limit = value; }
        }

        [Column("smtp_server")]
        public string? SmtpServer
        {
            get { return data.smtp_server; }
            set { data.smtp_server = value; }
        }

        [Column("use_tls")]
        public int UseTls
        {
            get { return data.use_tls; }
            set { data.use_tls = value; }
        }

        [Column("use_ssl_for_outgoing")]
        public int UseSslForOutgoing
        {
            get { return data.use_ssl_for_outgoing; }
            set { data.use_ssl_for_outgoing = value; }
        }

        [Column("smtp_port")]
        public string? SmtpPort
        {
            get { return data.smtp_port; }
            set { data.smtp_port = value; }
        }

        [Column("append_emails_to_sent_folder")]
        public int AppendEmailsToSentFolder
        {
            get { return data.append_emails_to_sent_folder; }
            set { data.append_emails_to_sent_folder = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

