/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/13/2022 7:48:39 PM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;
using System.Text.Json;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Desk.NotificationSettings
{
    public partial class ERP_Desk_NotificationSettings : ERPNextObjectBase
    {
        public ERP_Desk_NotificationSettings() : this(new ERPObject(_DocType.Desk_NotificationSettings)) { }
        public ERP_Desk_NotificationSettings(ERPObject obj) : base(obj) { }

        //public static string? GetColumnName(string propertyName)
        //{
        //    return ERPNextObjectBase.GetColumnName<ERP_Desk_NotificationSettings>(propertyName);
        //}

        //public static string? GetPropertyName(string columnName)
        //{
        //    return ERPNextObjectBase.GetPropertyName<ERP_Desk_NotificationSettings>(columnName);
        //}

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("enabled", "int(1)", isNullable: false)]
        public bool Enabled
        {
            get { return ERPNextConverter.IntToBool((int)data.enabled); }
            set { data.enabled = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("enable_email_notifications", "int(1)", isNullable: false)]
        public bool EnableEmailNotifications
        {
            get { return ERPNextConverter.IntToBool((int)data.enable_email_notifications); }
            set { data.enable_email_notifications = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("enable_email_mention", "int(1)", isNullable: false)]
        public bool EnableEmailMention
        {
            get { return ERPNextConverter.IntToBool((int)data.enable_email_mention); }
            set { data.enable_email_mention = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("enable_email_assignment", "int(1)", isNullable: false)]
        public bool EnableEmailAssignment
        {
            get { return ERPNextConverter.IntToBool((int)data.enable_email_assignment); }
            set { data.enable_email_assignment = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("enable_email_energy_point", "int(1)", isNullable: false)]
        public bool EnableEmailEnergyPoint
        {
            get { return ERPNextConverter.IntToBool((int)data.enable_email_energy_point); }
            set { data.enable_email_energy_point = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("enable_email_share", "int(1)", isNullable: false)]
        public bool EnableEmailShare
        {
            get { return ERPNextConverter.IntToBool((int)data.enable_email_share); }
            set { data.enable_email_share = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("enable_email_event_reminders", "int(1)", isNullable: false)]
        public bool EnableEmailEventReminders
        {
            get { return ERPNextConverter.IntToBool((int)data.enable_email_event_reminders); }
            set { data.enable_email_event_reminders = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("user", "varchar(140)", isNullable: true)]
        public string? User
        {
            get { return data.user; }
            set { data.user = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("seen", "int(1)", isNullable: false)]
        public bool Seen
        {
            get { return ERPNextConverter.IntToBool((int)data.seen); }
            set { data.seen = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("energy_points_system_notifications", "int(1)", isNullable: false)]
        public bool EnergyPointsSystemNotifications
        {
            get { return ERPNextConverter.IntToBool((int)data.energy_points_system_notifications); }
            set { data.energy_points_system_notifications = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("_user_tags", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [ColumnInfo("_comments", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [ColumnInfo("_assign", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [ColumnInfo("_liked_by", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

