/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Telephony.IncomingCallSettings
{
    public class Telephony_IncomingCallSettings_Service : SubServiceBase<ERP_Telephony_IncomingCallSettings>
    {
        public Telephony_IncomingCallSettings_Service(ERPNextClient client) : base(_DockType.Telephony_IncomingCallSettings, client) { }

        protected override ERP_Telephony_IncomingCallSettings FromERPObject(ERPObject obj)
        {
            return new ERP_Telephony_IncomingCallSettings(obj);
        }

        /* custom functions can be added here */

    }
}

