/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Website.WebFormField
{
    public partial class ERP_Website_WebFormField : ERPNextObjectBase
    {
        public ERP_Website_WebFormField() : this(new ERPObject(_DockType.Website_WebFormField)) { }
        public ERP_Website_WebFormField(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Website_WebFormField>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("fieldname")]
        public string? Fieldname
        {
            get { return data.fieldname; }
            set { data.fieldname = value; }
        }

        [Column("fieldtype")]
        public string? Fieldtype
        {
            get { return data.fieldtype; }
            set { data.fieldtype = value; }
        }

        [Column("label")]
        public string? Label
        {
            get { return data.label; }
            set { data.label = value; }
        }

        [Column("allow_read_on_all_link_options")]
        public int AllowReadOnAllLinkOptions
        {
            get { return data.allow_read_on_all_link_options; }
            set { data.allow_read_on_all_link_options = value; }
        }

        [Column("reqd")]
        public int Reqd
        {
            get { return data.reqd; }
            set { data.reqd = value; }
        }

        [Column("read_only")]
        public int ReadOnly
        {
            get { return data.read_only; }
            set { data.read_only = value; }
        }

        [Column("show_in_filter")]
        public int ShowInFilter
        {
            get { return data.show_in_filter; }
            set { data.show_in_filter = value; }
        }

        [Column("hidden")]
        public int Hidden
        {
            get { return data.hidden; }
            set { data.hidden = value; }
        }

        [Column("options")]
        public string? Options
        {
            get { return data.options; }
            set { data.options = value; }
        }

        [Column("max_length")]
        public int MaxLength
        {
            get { return data.max_length; }
            set { data.max_length = value; }
        }

        [Column("max_value")]
        public int MaxValue
        {
            get { return data.max_value; }
            set { data.max_value = value; }
        }

        [Column("depends_on")]
        public string? DependsOn
        {
            get { return data.depends_on; }
            set { data.depends_on = value; }
        }

        [Column("mandatory_depends_on")]
        public string? MandatoryDependsOn
        {
            get { return data.mandatory_depends_on; }
            set { data.mandatory_depends_on = value; }
        }

        [Column("read_only_depends_on")]
        public string? ReadOnlyDependsOn
        {
            get { return data.read_only_depends_on; }
            set { data.read_only_depends_on = value; }
        }

        [Column("description")]
        public string? Description
        {
            get { return data.description; }
            set { data.description = value; }
        }

        [Column("@default")]
        public string? Default
        {
            get { return data.@default; }
            set { data.@default = value; }
        }

        [Column("parent")]
        public string? Parent
        {
            get { return data.parent; }
            set { data.parent = value; }
        }

        [Column("parentfield")]
        public string? Parentfield
        {
            get { return data.parentfield; }
            set { data.parentfield = value; }
        }

        [Column("parenttype")]
        public string? Parenttype
        {
            get { return data.parenttype; }
            set { data.parenttype = value; }
        }


    }
}

