/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Telephony.TelephonyCallType
{
    public class Telephony_TelephonyCallType_Service : SubServiceBase<ERP_Telephony_TelephonyCallType>
    {
        public Telephony_TelephonyCallType_Service(ERPNextClient client) : base(_DockType.Telephony_TelephonyCallType, client) { }

        protected override ERP_Telephony_TelephonyCallType FromERPObject(ERPObject obj)
        {
            return new ERP_Telephony_TelephonyCallType(obj);
        }

        /* custom functions can be added here */

    }
}

