/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Custom.ClientScript
{
    public class Custom_ClientScript_Service : SubServiceBase<ERP_Custom_ClientScript>
    {
        public Custom_ClientScript_Service(ERPNextClient client) : base(_DockType.Custom_ClientScript, client) { }

        protected override ERP_Custom_ClientScript FromERPObject(ERPObject obj)
        {
            return new ERP_Custom_ClientScript(obj);
        }

        /* custom functions can be added here */

    }
}

