/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/14/2022 8:42:56 AM
********************************************************************/

using System;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using GizmoFort.Connector.ERPNext.DataAnnotations;
using GizmoFort.Connector.ERPNext.Serialization;
using _DocType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Setup.EmailDigest
{
    public partial class ERP_Setup_EmailDigest : ERPNextObjectBase
    {
        public ERP_Setup_EmailDigest() : this(new ERPObject(_DocType.Setup_EmailDigest)) { }
        public ERP_Setup_EmailDigest(ERPObject obj) : base(obj) { }

        [ColumnInfo("name", "varchar(140)", isNullable: false)]
        public string Name
        {
            get { return data.name; }
            set { data.name = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("creation", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Creation
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.creation); }
            set { data.creation = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified", "datetime(6)", isNullable: true)]
        public DateTimeOffset? Modified
        {
            get { return ERPNextConverter.StringToDateTimeOffset(data.modified); }
            set { data.modified = ERPNextConverter.DateTimeOffsetToString(value, 6); }
        }

        [ColumnInfo("modified_by", "varchar(140)", isNullable: true)]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("owner", "varchar(140)", isNullable: true)]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("docstatus", "int(1)", isNullable: false)]
        public Docstatus Docstatus
        {
            get { return (Docstatus)data.docstatus; }
            set { data.docstatus = (int)value; }
        }

        [ColumnInfo("idx", "int(8)", isNullable: false)]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [ColumnInfo("enabled", "int(1)", isNullable: false)]
        public bool Enabled
        {
            get { return ERPNextConverter.IntToBool((int)data.enabled); }
            set { data.enabled = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("company", "varchar(140)", isNullable: true)]
        public string? Company
        {
            get { return data.company; }
            set { data.company = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("frequency", "varchar(140)", isNullable: true)]
        public string? Frequency
        {
            get { return data.frequency; }
            set { data.frequency = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("next_send", "varchar(140)", isNullable: true)]
        public string? NextSend
        {
            get { return data.next_send; }
            set { data.next_send = ERPNextConverter.TruncateString(value, 140); }
        }

        [ColumnInfo("income", "int(1)", isNullable: false)]
        public bool Income
        {
            get { return ERPNextConverter.IntToBool((int)data.income); }
            set { data.income = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("expenses_booked", "int(1)", isNullable: false)]
        public bool ExpensesBooked
        {
            get { return ERPNextConverter.IntToBool((int)data.expenses_booked); }
            set { data.expenses_booked = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("income_year_to_date", "int(1)", isNullable: false)]
        public bool IncomeYearToDate
        {
            get { return ERPNextConverter.IntToBool((int)data.income_year_to_date); }
            set { data.income_year_to_date = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("expense_year_to_date", "int(1)", isNullable: false)]
        public bool ExpenseYearToDate
        {
            get { return ERPNextConverter.IntToBool((int)data.expense_year_to_date); }
            set { data.expense_year_to_date = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("bank_balance", "int(1)", isNullable: false)]
        public bool BankBalance
        {
            get { return ERPNextConverter.IntToBool((int)data.bank_balance); }
            set { data.bank_balance = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("credit_balance", "int(1)", isNullable: false)]
        public bool CreditBalance
        {
            get { return ERPNextConverter.IntToBool((int)data.credit_balance); }
            set { data.credit_balance = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("invoiced_amount", "int(1)", isNullable: false)]
        public bool InvoicedAmount
        {
            get { return ERPNextConverter.IntToBool((int)data.invoiced_amount); }
            set { data.invoiced_amount = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("payables", "int(1)", isNullable: false)]
        public bool Payables
        {
            get { return ERPNextConverter.IntToBool((int)data.payables); }
            set { data.payables = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("sales_orders_to_bill", "int(1)", isNullable: false)]
        public bool SalesOrdersToBill
        {
            get { return ERPNextConverter.IntToBool((int)data.sales_orders_to_bill); }
            set { data.sales_orders_to_bill = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("purchase_orders_to_bill", "int(1)", isNullable: false)]
        public bool PurchaseOrdersToBill
        {
            get { return ERPNextConverter.IntToBool((int)data.purchase_orders_to_bill); }
            set { data.purchase_orders_to_bill = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("sales_order", "int(1)", isNullable: false)]
        public bool SalesOrder
        {
            get { return ERPNextConverter.IntToBool((int)data.sales_order); }
            set { data.sales_order = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("purchase_order", "int(1)", isNullable: false)]
        public bool PurchaseOrder
        {
            get { return ERPNextConverter.IntToBool((int)data.purchase_order); }
            set { data.purchase_order = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("sales_orders_to_deliver", "int(1)", isNullable: false)]
        public bool SalesOrdersToDeliver
        {
            get { return ERPNextConverter.IntToBool((int)data.sales_orders_to_deliver); }
            set { data.sales_orders_to_deliver = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("purchase_orders_to_receive", "int(1)", isNullable: false)]
        public bool PurchaseOrdersToReceive
        {
            get { return ERPNextConverter.IntToBool((int)data.purchase_orders_to_receive); }
            set { data.purchase_orders_to_receive = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("sales_invoice", "int(1)", isNullable: false)]
        public bool SalesInvoice
        {
            get { return ERPNextConverter.IntToBool((int)data.sales_invoice); }
            set { data.sales_invoice = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("purchase_invoice", "int(1)", isNullable: false)]
        public bool PurchaseInvoice
        {
            get { return ERPNextConverter.IntToBool((int)data.purchase_invoice); }
            set { data.purchase_invoice = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("new_quotations", "int(1)", isNullable: false)]
        public bool NewQuotations
        {
            get { return ERPNextConverter.IntToBool((int)data.new_quotations); }
            set { data.new_quotations = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("pending_quotations", "int(1)", isNullable: false)]
        public bool PendingQuotations
        {
            get { return ERPNextConverter.IntToBool((int)data.pending_quotations); }
            set { data.pending_quotations = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("issue", "int(1)", isNullable: false)]
        public bool Issue
        {
            get { return ERPNextConverter.IntToBool((int)data.issue); }
            set { data.issue = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("project", "int(1)", isNullable: false)]
        public bool Project
        {
            get { return ERPNextConverter.IntToBool((int)data.project); }
            set { data.project = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("purchase_orders_items_overdue", "int(1)", isNullable: false)]
        public bool PurchaseOrdersItemsOverdue
        {
            get { return ERPNextConverter.IntToBool((int)data.purchase_orders_items_overdue); }
            set { data.purchase_orders_items_overdue = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("calendar_events", "int(1)", isNullable: false)]
        public bool CalendarEvents
        {
            get { return ERPNextConverter.IntToBool((int)data.calendar_events); }
            set { data.calendar_events = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("todo_list", "int(1)", isNullable: false)]
        public bool TodoList
        {
            get { return ERPNextConverter.IntToBool((int)data.todo_list); }
            set { data.todo_list = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("notifications", "int(1)", isNullable: false)]
        public bool Notifications
        {
            get { return ERPNextConverter.IntToBool((int)data.notifications); }
            set { data.notifications = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("add_quote", "int(1)", isNullable: false)]
        public bool AddQuote
        {
            get { return ERPNextConverter.IntToBool((int)data.add_quote); }
            set { data.add_quote = ERPNextConverter.BoolToInt(value); }
        }

        [ColumnInfo("_user_tags", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [ColumnInfo("_comments", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [ColumnInfo("_assign", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [ColumnInfo("_liked_by", "text", isNullable: true)]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

