/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/9/2022 12:40:42 AM
********************************************************************/

using System;
using System.ComponentModel.DataAnnotations.Schema;
using GizmoFort.Connector.ERPNext.PublicTypes;
using GizmoFort.Connector.ERPNext.WrapperTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Accounts.ShareTransfer
{
    public partial class ERP_Accounts_ShareTransfer : ERPNextObjectBase
    {
        public ERP_Accounts_ShareTransfer() : this(new ERPObject(_DockType.Accounts_ShareTransfer)) { }
        public ERP_Accounts_ShareTransfer(ERPObject obj) : base(obj) { }

        public static string? GetColumnName(string propertyName)
        {
            return ERPNextObjectBase.GetColumnName<ERP_Accounts_ShareTransfer>(propertyName);
        }

        [Column("name")]
        public string Name
        {
            get { return data.name; }
            set { data.name = value; }
        }

        [Column("creation")]
        public DateTime? Creation
        {
            get { return data.creation; }
            set { data.creation = value; }
        }

        [Column("modified")]
        public DateTime? Modified
        {
            get { return data.modified; }
            set { data.modified = value; }
        }

        [Column("modified_by")]
        public string? ModifiedBy
        {
            get { return data.modified_by; }
            set { data.modified_by = value; }
        }

        [Column("owner")]
        public string? Owner
        {
            get { return data.owner; }
            set { data.owner = value; }
        }

        [Column("docstatus")]
        public int Docstatus
        {
            get { return data.docstatus; }
            set { data.docstatus = value; }
        }

        [Column("idx")]
        public int Idx
        {
            get { return data.idx; }
            set { data.idx = value; }
        }

        [Column("transfer_type")]
        public string? TransferType
        {
            get { return data.transfer_type; }
            set { data.transfer_type = value; }
        }

        [Column("date")]
        public DateOnly? Date
        {
            get { return data.date; }
            set { data.date = value; }
        }

        [Column("from_shareholder")]
        public string? FromShareholder
        {
            get { return data.from_shareholder; }
            set { data.from_shareholder = value; }
        }

        [Column("from_folio_no")]
        public string? FromFolioNo
        {
            get { return data.from_folio_no; }
            set { data.from_folio_no = value; }
        }

        [Column("to_shareholder")]
        public string? ToShareholder
        {
            get { return data.to_shareholder; }
            set { data.to_shareholder = value; }
        }

        [Column("to_folio_no")]
        public string? ToFolioNo
        {
            get { return data.to_folio_no; }
            set { data.to_folio_no = value; }
        }

        [Column("equity_or_liability_account")]
        public string? EquityOrLiabilityAccount
        {
            get { return data.equity_or_liability_account; }
            set { data.equity_or_liability_account = value; }
        }

        [Column("asset_account")]
        public string? AssetAccount
        {
            get { return data.asset_account; }
            set { data.asset_account = value; }
        }

        [Column("share_type")]
        public string? ShareType
        {
            get { return data.share_type; }
            set { data.share_type = value; }
        }

        [Column("from_no")]
        public int FromNo
        {
            get { return data.from_no; }
            set { data.from_no = value; }
        }

        [Column("rate")]
        public decimal Rate
        {
            get { return data.rate; }
            set { data.rate = value; }
        }

        [Column("no_of_shares")]
        public int NoOfShares
        {
            get { return data.no_of_shares; }
            set { data.no_of_shares = value; }
        }

        [Column("to_no")]
        public int ToNo
        {
            get { return data.to_no; }
            set { data.to_no = value; }
        }

        [Column("amount")]
        public decimal Amount
        {
            get { return data.amount; }
            set { data.amount = value; }
        }

        [Column("company")]
        public string? Company
        {
            get { return data.company; }
            set { data.company = value; }
        }

        [Column("remarks")]
        public string? Remarks
        {
            get { return data.remarks; }
            set { data.remarks = value; }
        }

        [Column("amended_from")]
        public string? AmendedFrom
        {
            get { return data.amended_from; }
            set { data.amended_from = value; }
        }

        [Column("_user_tags")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _UserTags
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._user_tags; }
            set { data._user_tags = value; }
        }

        [Column("_comments")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Comments
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._comments; }
            set { data._comments = value; }
        }

        [Column("_assign")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _Assign
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._assign; }
            set { data._assign = value; }
        }

        [Column("_liked_by")]
#pragma warning disable IDE1006 // Naming Styles
        public string? _LikedBy
#pragma warning restore IDE1006 // Naming Styles
        {
            get { return data._liked_by; }
            set { data._liked_by = value; }
        }


    }
}

