/********************************************************************
    This file has been auto-generated by GenerateCodeFromSchemaJson
    created date: 9/8/2022 10:56:52 PM
********************************************************************/

using GizmoFort.Connector.ERPNext.PublicInterfaces;
using GizmoFort.Connector.ERPNext.PublicInterfaces.SubServices;
using GizmoFort.Connector.ERPNext.PublicTypes;
using _DockType = GizmoFort.Connector.ERPNext.PublicTypes.DocType;

namespace GizmoFort.Connector.ERPNext.ERPTypes.Assets.AssetMaintenance
{
    public class Assets_AssetMaintenance_Service : SubServiceBase<ERP_Assets_AssetMaintenance>
    {
        public Assets_AssetMaintenance_Service(ERPNextClient client) : base(_DockType.Assets_AssetMaintenance, client) { }

        protected override ERP_Assets_AssetMaintenance FromERPObject(ERPObject obj)
        {
            return new ERP_Assets_AssetMaintenance(obj);
        }

        /* custom functions can be added here */

    }
}

